#Integer

adalh tnp desimal

In [45]:
x=18
print(x)

18


In [46]:
x=17
x

17

In [47]:
x=30
x

30

In [48]:
y=-35
print(y)

-35


In [49]:
type(x)

int

In [50]:
print(type(y))

<class 'int'>


#float

pake desimal

In [51]:
x=1.51
print(x)

1.51


In [52]:
y=-9.921
print(y)

-9.921


In [53]:
print(type(x))

<class 'float'>


#basic operation with integer and float


In [54]:
x=7
y=3

In [55]:
print(x-y)

4


In [56]:
print(x+y)

10


In [57]:
x+y

10

In [58]:
print(x/y)

2.3333333333333335


In [59]:
a=x/y
print(a)

2.3333333333333335


In [60]:
round(x/y,2)

2.33

In [61]:
print(x/y)

2.3333333333333335


In [62]:
a=x/y
print(a)

2.3333333333333335


In [63]:
round(x/y,4)

2.3333

In [64]:
print(x*y)

21


In [65]:
x=7
y=3
print(x//y)

2


In [66]:
import math

b=x/y
print(b)
print(math.ceil(b))

2.3333333333333335
3


In [67]:
print(x**y)
print(y**(0.5))

343
1.7320508075688772


In [68]:
print(9**3)

729


In [69]:
import math
b=5.2
print(math.ceil(b))

6


In [70]:
c=5.99923987
print(math.floor(c))

5


#Boolean

In [71]:
x=False
y=True

In [72]:
print(x)

False


In [73]:
print(y)

True


In [74]:
print('Penjumlahan x+y=',x+y)
print('Pengurangan x-y=',x-y)
print('Perkalian x*y=',x*y)
print('Pangkat x**y=',x**y)
print('Pembagian x/y=',x/y)

Penjumlahan x+y= 1
Pengurangan x-y= -1
Perkalian x*y= 0
Pangkat x**y= 0
Pembagian x/y= 0.0


In [75]:
print(type(y))

<class 'bool'>


#String

In [76]:
x='robbers'
y="1975"
z="ra'if 14!"

In [77]:
print('x tipe datany:',type(x))
print('y tipe datany:',type(y))
print('z tipe datany:',type(z))

x tipe datany: <class 'str'>
y tipe datany: <class 'str'>
z tipe datany: <class 'str'>


In [78]:
"Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist"

'Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist'

In [79]:
text="""
      Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist.Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist.Python merupakan bhs pemrograman yang sangt berguna utk seorang Data ScientistPython merupakan
      bhs pemrograman yang sangt berguna utk seorang Data Scientist
"""
print(text)


      Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist.Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist.Python merupakan bhs pemrograman yang sangt berguna utk seorang Data ScientistPython merupakan
      bhs pemrograman yang sangt berguna utk seorang Data Scientist



In [80]:
contoh='''
     Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist.
Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist. Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist. Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist. Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist. Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist.
  '''
print(contoh)


     Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist.
Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist. Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist. Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist. Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist. Python merupakan bhs pemrograman yang sangt berguna utk seorang Data Scientist.
  


In [81]:
nama="saya Arianty adlh seorang data scientis"
print(nama)

saya Arianty adlh seorang data scientis


#Basic Calculation with String

In [82]:
print(x)
print(y)

robbers
1975


In [83]:
print(x+y)

robbers1975


In [84]:
print(x-y)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [86]:
print(x*y)

TypeError: can't multiply sequence by non-int of type 'str'

In [ ]:
print(x/y)

In [ ]:
print(x)

In [ ]:
print(x*3)

In [ ]:
print((x+' ')*3)

#slicing can't apply in float, int, boolean

In [87]:
x=True
y=False
a=(x*y)
print('Hasil perkalian a=',a)
print(a[0:])

Hasil perkalian a= 0


TypeError: 'int' object is not subscriptable

In [89]:
x=3
y=4
a=(x*y)
print('Hasil perkalian a:',a)
print(a[1:])

Hasil perkalian a: 12


TypeError: 'int' object is not subscriptable

In [90]:
x=3
y=4.5
a=(x*y)
print('Hasil perkalian a=',a)


Hasil perkalian a= 13.5


In [91]:
print(a(1:))

SyntaxError: invalid syntax (<ipython-input-91-35ab839315c9>, line 1)

#Non-Primitive Data Structures


#List

In [92]:
lst_1=['a','b','c','d','e','f','g']
print(lst_1)

['a', 'b', 'c', 'd', 'e', 'f', 'g']


In [93]:
print(type(lst_1))

<class 'list'>


In [94]:
lst_2=['b','a',5,False,8.7]
print(lst_2)

['b', 'a', 5, False, 8.7]


In [95]:
print(type(lst_2))

<class 'list'>


#Basic Operations with List

In [96]:
print(lst_1+lst_2)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'b', 'a', 5, False, 8.7]


In [97]:
print(lst_1[1:4])

['b', 'c', 'd']


In [98]:
print(lst_1[1:4])
print(lst_1[-3:])
print(lst_2[2:])

['b', 'c', 'd']
['e', 'f', 'g']
[5, False, 8.7]


In [99]:
#mengakses spesifik value
print(lst_1[3])

d


In [100]:
#mengganti spesific value
lst_1[3]=12.69
print(lst_1)

['a', 'b', 'c', 12.69, 'e', 'f', 'g']


In [101]:
#mengganti range nilai
lst_1[3:]=['z','e','a', True,1,30.5]
print(lst_1)

['a', 'b', 'c', 'z', 'e', 'a', True, 1, 30.5]


In [102]:
#menambahkan nilai baru di akhir list
lst_1.append('g')
print(lst_1)

['a', 'b', 'c', 'z', 'e', 'a', True, 1, 30.5, 'g']


In [103]:
lst_2

['b', 'a', 5, False, 8.7]

In [104]:
#checking if a value is contained in the list
'z' in lst_1

True

In [105]:
#Join list elements into string
lst_1=['a','b','c','z','e','g']
print(''.join(lst_1))
print('_'.join(lst_1))
print(type(lst_1))


abczeg
a_b_c_z_e_g
<class 'list'>


In [106]:
print(lst_1)

['a', 'b', 'c', 'z', 'e', 'g']


In [107]:
del lst_1[1]

In [108]:
lst_1

['a', 'c', 'z', 'e', 'g']

In [109]:
print(lst_1)

['a', 'c', 'z', 'e', 'g']


In [110]:
del lst_1[1:4]

In [111]:
print(lst_1)

['a', 'g']


In [112]:
a=0

In [114]:
lst_1=['a','b','c','d','e','f','g']
lst_1.pop(a)
print(lst_1)

['b', 'c', 'd', 'e', 'f', 'g']


In [115]:
print(lst_1)

['b', 'c', 'd', 'e', 'f', 'g']


#Arrays

In [116]:
import numpy as np

In [117]:
arr_1=np.array([1,2,3,4,5,6.5,True,False])

In [118]:
print(arr_1)

[1.  2.  3.  4.  5.  6.5 1.  0. ]


In [119]:
'a','b',5,3

('a', 'b', 5, 3)

In [120]:
arr_mixed_1=np.array(['a','b',5,3])

In [121]:
print(arr_mixed_1)

['a' 'b' '5' '3']


In [122]:
arr_mixed_2=np.array([1,4,5,7,True])

In [123]:
print(arr_mixed_2)

[1 4 5 7 1]


In [126]:
arr_mixed_2=np.array([1,4,5,7,True])
print(arr_mixed_2)

[1 4 5 7 1]


In [127]:
arr_ones=np.ones(3)

In [128]:
print(arr_ones)

[1. 1. 1.]


In [129]:
arr_zeros=np.zeros(7)

In [130]:
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0.]


#Basic Operations with Numpy Array

In [131]:
arr_1=np.array([1,2,3,4,5])
print(arr_1)

[1 2 3 4 5]


In [138]:
arr_2=np.ones(5)*3
print(arr_2)

[3. 3. 3. 3. 3.]


In [139]:
#substraction

print(arr_1-arr_2)

[-2. -1.  0.  1.  2.]


In [141]:
print(arr_1+arr_2)

[4. 5. 6. 7. 8.]


In [143]:
#multplication
print(arr_1*arr_2)

[ 3.  6.  9. 12. 15.]


In [144]:
#Division

print(arr_1/arr_2)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [145]:
#floor division

print(arr_1//arr_2)

[0. 0. 1. 1. 1.]


In [146]:
print(arr_2)

[3. 3. 3. 3. 3.]


In [147]:
maximum_arr_2=np.max(arr_2)

In [148]:
print(maximum_arr_2)

3.0


In [149]:
minimum_arr_2=np.min(arr_2)

In [150]:
print(minimum_arr_2)

3.0


#Matrix


In [151]:
mat_1=np.array([[5,6],[7,8]])
print(mat_1)

[[5 6]
 [7 8]]


In [152]:
print(mat_1.shape)

(2, 2)


In [153]:
mat_2=np.array([[9,10],[11,12]])
print(mat_2)

[[ 9 10]
 [11 12]]


In [154]:
np.hstack([mat_1,mat_2])

array([[ 5,  6,  9, 10],
       [ 7,  8, 11, 12]])

In [155]:
np.vstack([mat_1,mat_2])

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

#Basic Operations with Matrix


In [156]:
print(mat_1)

[[5 6]
 [7 8]]


In [157]:
print(mat_2)

[[ 9 10]
 [11 12]]


In [158]:
print(mat_1+mat_2)

[[14 16]
 [18 20]]


In [159]:
print(mat_1-mat_2)

[[-4 -4]
 [-4 -4]]


In [160]:
print(mat_1*mat_2)

[[45 60]
 [77 96]]


In [161]:
print(mat_1/mat_2)

[[0.55555556 0.6       ]
 [0.63636364 0.66666667]]


In [162]:
print(mat_1)

[[5 6]
 [7 8]]


In [163]:
#elemen di baris 0, kolom 0
print(mat_1[0,0])

5


In [164]:
print(mat_1[0,1])

6


In [165]:
print(mat_1[0,:])

[5 6]


In [166]:
print(mat_1[:,0])

[5 7]


In [ ]:
print(mat_1)

#Tuple

In [167]:
tuple_1=(1,2,1)

In [168]:
print(tuple_1)

(1, 2, 1)


In [169]:
tuple_2=7,8,9
print(tuple_2)

(7, 8, 9)


In [170]:
#mengambil pd indeks slice ttt
print(tuple_1[-2])

2


In [171]:
print(tuple_1+tuple_2)

(1, 2, 1, 7, 8, 9)


In [172]:
tuple_1[0]=2

TypeError: 'tuple' object does not support item assignment

In [173]:
print(tuple_1-tuple_2)

TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

#Set

In [174]:
#BIA BERISI TPE DATA PRIMITIVE CAMPURAN (INT, BOOL. FLOAT, STRING)

set_1={1,2,3,4,4,4,4,5,5,5,6,'a','z','b',True,False}

In [175]:
print(set_1)

{'a', 1, 2, 3, 4, 5, 6, 'z', False, 'b'}


In [176]:
set_2=set([4,4,4,4,3,3,3,5,5,6,7])

In [177]:
print(set_2)

{3, 4, 5, 6, 7}


#Basic Operations with set

In [178]:
#pengurangan
print(set_1-set_2)

{'a', 1, 2, 'z', False, 'b'}


In [181]:
#elmts in both set_1 and set_2 (irisan)
print(set_1&set_2)

{3, 4, 5, 6}


In [182]:
#UNIOn
print(set_1|set_2)

{'a', 1, 2, 3, 4, 5, 6, 'z', False, 'b', 7}


In [183]:
print(set_1/set_2)

TypeError: unsupported operand type(s) for /: 'set' and 'set'

In [187]:
#make a test score each students

score_dict={'Bell':75,
            'John':96,
            'Shinta':83.3,
            'Mark':55,
            'Kurnia':90
            }
print(score_dict)

{'Bell': 75, 'John': 96, 'Shinta': 83.3, 'Mark': 55, 'Kurnia': 90}


#dictionary

In [188]:
print(score_dict['John'])
print(score_dict['Mark'])

96
55


In [190]:
#we can add change value of one student
score_dict['Bell']=77
print(score_dict)

{'Bell': 77, 'John': 96, 'Shinta': 83.3, 'Mark': 55, 'Kurnia': 90}


In [191]:
del score_dict['Shinta']
print(score_dict)

{'Bell': 77, 'John': 96, 'Mark': 55, 'Kurnia': 90}


In [192]:
#key and values
print(score_dict.keys())

dict_keys(['Bell', 'John', 'Mark', 'Kurnia'])


In [193]:
print(score_dict.values())

dict_values([77, 96, 55, 90])


In [198]:
score_dict['Haekal']=score_dict.pop('John')
score_dict

{'Bell': 77, 'Mark': 55, 'Kurnia': 90, 'Haekal': 96}

In [200]:
#vary  value dictionary-> just fyi
vary_value_dict={'Gender':'Male',
            'list':['Male',9,8,5.772,True],
            'array':np.array([1,6.5,True,False]),
            'matrix':np.array([[3,2],[4,7]]),
            'tuple':(1,3,7),
            'set':set([1,1,1,2,2,3]),
            'dictionary':{
                'key_1':'value1',
                'key_2':'value2'
            }
            }
vary_value_dict

{'Gender': 'Male',
 'list': ['Male', 9, 8, 5.772, True],
 'array': array([1. , 6.5, 1. , 0. ]),
 'matrix': array([[3, 2],
        [4, 7]]),
 'tuple': (1, 3, 7),
 'set': {1, 2, 3},
 'dictionary': {'key_1': 'value1', 'key_2': 'value2'}}